gan:
    batch_size: 3500
    input_dim: 40
    gen_hid_dim: 100
    latent_dim: 50
    dropout_p: 0.75
    lr: 0.0005
    max_length: 100
    amp_level: "O1"
seq2seq:
    batch_size: 1000
    enc_emb_dim: 50
    dec_emb_dim: 50
    enc_hid_dim: 50
    dec_hid_dim: 50
    latent_dim: 20
    dropout_p: 0.5
    attention: false
    lr: 0.0005
    teacher_forcing_ratio: 0.5
    max_length: 100
    amp_level: "O1"
